// Code generated by goyacc - DO NOT EDIT.

package parser

import __yyfmt__ "fmt"

import "github.com/tesujiro/exp_yacc/ast"

type yySymType struct {
	yys        int
	token      ast.Token
	stmt_if    ast.Stmt
	stmt       ast.Stmt
	stmts      []ast.Stmt
	expr       ast.Expr
	exprs      []ast.Expr
	ident_args []string
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57367
	yyEofCode = 57344
	ANDAND    = 57360
	BREAK     = 57364
	CONTINUE  = 57365
	ELSE      = 57359
	EQEQ      = 57354
	FALSE     = 57350
	FOR       = 57363
	FUNC      = 57352
	GE        = 57356
	IDENT     = 57346
	IF        = 57358
	LE        = 57357
	LEN       = 57362
	NEQ       = 57355
	NIL       = 57351
	NUMBER    = 57347
	OROR      = 57361
	RETURN    = 57353
	STRING    = 57348
	TRUE      = 57349
	UNARY     = 57366
	yyErrCode = 57345

	yyMaxDepth = 200
	yyTabOfs   = -62
)

var (
	yyPrec = map[int]int{
		'=':    0,
		OROR:   1,
		ANDAND: 2,
		IDENT:  3,
		EQEQ:   4,
		NEQ:    4,
		'>':    5,
		'<':    5,
		GE:     5,
		LE:     5,
		'+':    6,
		'-':    6,
		'*':    7,
		'/':    7,
		'%':    7,
		UNARY:  8,
	}

	yyXLAT = map[int]int{
		40:    0,  // '(' (89x)
		43:    1,  // '+' (86x)
		45:    2,  // '-' (86x)
		123:   3,  // '{' (83x)
		125:   4,  // '}' (75x)
		44:    5,  // ',' (70x)
		10:    6,  // '\n' (67x)
		57344: 7,  // $end (60x)
		59:    8,  // ';' (55x)
		57346: 9,  // IDENT (52x)
		61:    10, // '=' (49x)
		57350: 11, // FALSE (47x)
		57352: 12, // FUNC (47x)
		57362: 13, // LEN (47x)
		57351: 14, // NIL (47x)
		57347: 15, // NUMBER (47x)
		57348: 16, // STRING (47x)
		57349: 17, // TRUE (47x)
		41:    18, // ')' (44x)
		37:    19, // '%' (39x)
		42:    20, // '*' (39x)
		47:    21, // '/' (39x)
		60:    22, // '<' (39x)
		62:    23, // '>' (39x)
		91:    24, // '[' (39x)
		57360: 25, // ANDAND (39x)
		57354: 26, // EQEQ (39x)
		57356: 27, // GE (39x)
		57357: 28, // LE (39x)
		57355: 29, // NEQ (39x)
		57361: 30, // OROR (39x)
		57359: 31, // ELSE (38x)
		93:    32, // ']' (35x)
		57368: 33, // expr (30x)
		57358: 34, // IF (17x)
		57364: 35, // BREAK (16x)
		57365: 36, // CONTINUE (16x)
		57363: 37, // FOR (16x)
		57371: 38, // newLine (16x)
		57353: 39, // RETURN (16x)
		57372: 40, // newLines (13x)
		57369: 41, // exprs (8x)
		57374: 42, // opt_term (8x)
		57379: 43, // term (8x)
		57375: 44, // program (7x)
		57378: 45, // stmts (7x)
		57373: 46, // opt_newLines (4x)
		57370: 47, // ident_args (2x)
		57376: 48, // stmt (2x)
		57377: 49, // stmt_if (2x)
		57367: 50, // $default (0x)
		57345: 51, // error (0x)
		57366: 52, // UNARY (0x)
	}

	yySymNames = []string{
		"'('",
		"'+'",
		"'-'",
		"'{'",
		"'}'",
		"','",
		"'\\n'",
		"$end",
		"';'",
		"IDENT",
		"'='",
		"FALSE",
		"FUNC",
		"LEN",
		"NIL",
		"NUMBER",
		"STRING",
		"TRUE",
		"')'",
		"'%'",
		"'*'",
		"'/'",
		"'<'",
		"'>'",
		"'['",
		"ANDAND",
		"EQEQ",
		"GE",
		"LE",
		"NEQ",
		"OROR",
		"ELSE",
		"']'",
		"expr",
		"IF",
		"BREAK",
		"CONTINUE",
		"FOR",
		"newLine",
		"RETURN",
		"newLines",
		"exprs",
		"opt_term",
		"term",
		"program",
		"stmts",
		"opt_newLines",
		"ident_args",
		"stmt",
		"stmt_if",
		"$default",
		"error",
		"UNARY",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {44, 1},
		2:  {44, 2},
		3:  {45, 2},
		4:  {45, 3},
		5:  {48, 3},
		6:  {48, 3},
		7:  {48, 1},
		8:  {48, 4},
		9:  {48, 1},
		10: {48, 1},
		11: {48, 1},
		12: {49, 5},
		13: {49, 7},
		14: {49, 5},
		15: {49, 2},
		16: {41, 0},
		17: {41, 1},
		18: {41, 4},
		19: {33, 1},
		20: {33, 1},
		21: {33, 1},
		22: {33, 1},
		23: {33, 1},
		24: {33, 1},
		25: {33, 4},
		26: {33, 8},
		27: {33, 4},
		28: {33, 4},
		29: {33, 7},
		30: {33, 5},
		31: {33, 4},
		32: {33, 4},
		33: {33, 2},
		34: {33, 2},
		35: {33, 3},
		36: {33, 3},
		37: {33, 3},
		38: {33, 3},
		39: {33, 3},
		40: {33, 3},
		41: {33, 3},
		42: {33, 3},
		43: {33, 3},
		44: {33, 3},
		45: {33, 3},
		46: {33, 3},
		47: {33, 3},
		48: {33, 3},
		49: {47, 0},
		50: {47, 1},
		51: {47, 4},
		52: {42, 0},
		53: {42, 1},
		54: {43, 2},
		55: {43, 1},
		56: {43, 1},
		57: {46, 0},
		58: {46, 1},
		59: {40, 1},
		60: {40, 2},
		61: {38, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [127][]uint16{
		// 0
		{10, 10, 10, 10, 5: 10, 70, 10, 67, 10, 10, 10, 10, 10, 10, 10, 10, 10, 34: 10, 10, 10, 10, 69, 10, 68, 42: 64, 66, 63, 65},
		{7: 62},
		{95, 93, 94, 92, 61, 46, 7: 61, 9: 84, 46, 88, 90, 91, 89, 85, 86, 87, 33: 76, 82, 80, 81, 79, 39: 83, 41: 77, 48: 188, 78},
		{4: 10, 6: 70, 10, 67, 38: 69, 40: 68, 42: 73, 74},
		{9, 9, 9, 9, 9, 9, 7: 9, 9: 9, 9, 9, 9, 9, 9, 9, 9, 9, 34: 9, 9, 9, 9, 39: 9},
		// 5
		{6, 6, 6, 6, 6, 6, 70, 6, 9: 6, 6, 6, 6, 6, 6, 6, 6, 6, 34: 6, 6, 6, 6, 69, 6, 72},
		{7, 7, 7, 7, 7, 7, 70, 7, 9: 7, 7, 7, 7, 7, 7, 7, 7, 7, 34: 7, 7, 7, 7, 71, 7},
		{3, 3, 3, 3, 3, 3, 3, 3, 9: 3, 3, 3, 3, 3, 3, 3, 3, 3, 34: 3, 3, 3, 3, 39: 3},
		{1, 1, 1, 1, 1, 1, 1, 1, 9: 1, 1, 1, 1, 1, 1, 1, 1, 1, 34: 1, 1, 1, 1, 39: 1},
		{2, 2, 2, 2, 2, 2, 2, 2, 9: 2, 2, 2, 2, 2, 2, 2, 2, 2, 34: 2, 2, 2, 2, 39: 2},
		// 10
		{8, 8, 8, 8, 8, 8, 70, 8, 9: 8, 8, 8, 8, 8, 8, 8, 8, 8, 34: 8, 8, 8, 8, 71, 8},
		{4: 60, 7: 60},
		{95, 93, 94, 92, 9, 46, 7: 9, 9: 84, 46, 88, 90, 91, 89, 85, 86, 87, 33: 76, 82, 80, 81, 79, 39: 83, 41: 77, 48: 75, 78},
		{4: 58, 6: 58, 58, 58},
		{97, 102, 103, 4: 51, 45, 51, 51, 51, 10: 186, 19: 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 100},
		// 15
		{5: 128, 10: 184},
		{4: 55, 6: 55, 55, 55, 31: 175},
		{3: 172},
		{4: 53, 6: 53, 53, 53},
		{4: 52, 6: 52, 52, 52},
		// 20
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 168},
		{95, 93, 94, 92, 46, 46, 46, 46, 46, 84, 11: 88, 90, 91, 89, 85, 86, 87, 31: 46, 33: 126, 41: 167},
		{161, 43, 43, 43, 43, 43, 43, 43, 43, 10: 43, 18: 43, 43, 43, 43, 43, 43, 162, 43, 43, 43, 43, 43, 43, 43, 43},
		{42, 42, 42, 42, 42, 42, 42, 42, 42, 10: 42, 18: 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42},
		{41, 41, 41, 41, 41, 41, 41, 41, 41, 10: 41, 18: 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41},
		// 25
		{40, 40, 40, 40, 40, 40, 40, 40, 40, 10: 40, 18: 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40},
		{39, 39, 39, 39, 39, 39, 39, 39, 39, 10: 39, 18: 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39},
		{38, 38, 38, 38, 38, 38, 38, 38, 38, 10: 38, 18: 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38},
		{145, 9: 144},
		{141},
		// 30
		{5, 5, 5, 5, 5, 5, 70, 9: 5, 11: 5, 5, 5, 5, 5, 5, 5, 38: 69, 40: 131, 46: 137},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 136},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 135},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 96},
		{97, 102, 103, 18: 99, 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 100},
		// 35
		{95, 93, 94, 92, 5: 46, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 46, 33: 126, 41: 133},
		{95, 93, 94, 92, 5: 46, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 32: 46, 126, 41: 127},
		{27, 27, 27, 27, 27, 27, 27, 27, 27, 10: 27, 18: 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 125},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 124},
		// 40
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 123},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 122},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 121},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 120},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 119},
		// 45
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 118},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 117},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 116},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 115},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 114},
		// 50
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 113},
		{97, 102, 103, 14, 14, 14, 14, 14, 14, 10: 14, 18: 14, 106, 104, 105, 14, 14, 98, 14, 14, 14, 14, 14, 14, 14, 14},
		{97, 102, 103, 15, 15, 15, 15, 15, 15, 10: 15, 18: 15, 106, 104, 105, 15, 15, 98, 15, 15, 15, 15, 15, 15, 15, 15},
		{97, 102, 103, 16, 16, 16, 16, 16, 16, 10: 16, 18: 16, 106, 104, 105, 16, 16, 98, 16, 16, 16, 16, 16, 16, 16, 16},
		{97, 102, 103, 17, 17, 17, 17, 17, 17, 10: 17, 18: 17, 106, 104, 105, 17, 17, 98, 17, 17, 17, 17, 17, 17, 17, 17},
		// 55
		{97, 102, 103, 18, 18, 18, 18, 18, 18, 10: 18, 18: 18, 106, 104, 105, 110, 109, 98, 18, 18, 111, 112, 18, 18, 18, 18},
		{97, 102, 103, 19, 19, 19, 19, 19, 19, 10: 19, 18: 19, 106, 104, 105, 110, 109, 98, 19, 19, 111, 112, 19, 19, 19, 19},
		{97, 20, 20, 20, 20, 20, 20, 20, 20, 10: 20, 18: 20, 20, 20, 20, 20, 20, 98, 20, 20, 20, 20, 20, 20, 20, 20},
		{97, 21, 21, 21, 21, 21, 21, 21, 21, 10: 21, 18: 21, 21, 21, 21, 21, 21, 98, 21, 21, 21, 21, 21, 21, 21, 21},
		{97, 22, 22, 22, 22, 22, 22, 22, 22, 10: 22, 18: 22, 22, 22, 22, 22, 22, 98, 22, 22, 22, 22, 22, 22, 22, 22},
		// 60
		{97, 23, 23, 23, 23, 23, 23, 23, 23, 10: 23, 18: 23, 106, 104, 105, 23, 23, 98, 23, 23, 23, 23, 23, 23, 23, 23},
		{97, 24, 24, 24, 24, 24, 24, 24, 24, 10: 24, 18: 24, 106, 104, 105, 24, 24, 98, 24, 24, 24, 24, 24, 24, 24, 24},
		{97, 102, 103, 25, 25, 25, 25, 25, 25, 10: 25, 18: 25, 106, 104, 105, 110, 109, 98, 25, 107, 111, 112, 108, 25, 25, 25},
		{97, 102, 103, 26, 26, 26, 26, 26, 26, 10: 26, 18: 26, 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 26, 26, 26},
		{97, 102, 103, 4: 45, 45, 45, 45, 45, 18: 45, 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 100, 45, 45},
		// 65
		{5: 128, 32: 129},
		{5, 5, 5, 5, 6: 70, 9: 5, 11: 5, 5, 5, 5, 5, 5, 5, 38: 69, 40: 131, 46: 130},
		{30, 30, 30, 30, 30, 30, 30, 30, 30, 10: 30, 18: 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 132},
		{4, 4, 4, 4, 4, 4, 70, 9: 4, 11: 4, 4, 4, 4, 4, 4, 4, 38: 71},
		// 70
		{97, 102, 103, 4: 44, 44, 44, 44, 44, 10: 44, 18: 44, 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 100, 44, 44},
		{5: 128, 18: 134},
		{34, 34, 34, 34, 34, 34, 34, 34, 34, 10: 34, 18: 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34},
		{97, 28, 28, 28, 28, 28, 28, 28, 28, 10: 28, 18: 28, 28, 28, 28, 28, 28, 98, 28, 28, 28, 28, 28, 28, 28, 28},
		{97, 29, 29, 29, 29, 29, 29, 29, 29, 10: 29, 18: 29, 29, 29, 29, 29, 29, 98, 29, 29, 29, 29, 29, 29, 29, 29},
		// 75
		{95, 93, 94, 92, 46, 46, 46, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 126, 41: 138},
		{4: 5, 128, 70, 38: 69, 40: 131, 46: 139},
		{4: 140},
		{32, 32, 32, 32, 32, 32, 32, 32, 32, 10: 32, 18: 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 142},
		// 80
		{97, 102, 103, 18: 143, 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 100},
		{35, 35, 35, 35, 35, 35, 35, 35, 35, 10: 35, 18: 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35},
		{155},
		{5: 13, 9: 147, 18: 13, 47: 146},
		{5: 149, 18: 148},
		// 85
		{5: 12, 18: 12},
		{3: 152},
		{6: 70, 9: 5, 38: 69, 40: 131, 46: 150},
		{9: 151},
		{5: 11, 18: 11},
		// 90
		{10, 10, 10, 10, 10, 10, 70, 8: 67, 10, 10, 10, 10, 10, 10, 10, 10, 10, 34: 10, 10, 10, 10, 69, 10, 68, 42: 64, 66, 153, 65},
		{4: 154},
		{33, 33, 33, 33, 33, 33, 33, 33, 33, 10: 33, 18: 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33},
		{5: 13, 9: 147, 18: 13, 47: 156},
		{5: 149, 18: 157},
		// 95
		{3: 158},
		{10, 10, 10, 10, 10, 10, 70, 8: 67, 10, 10, 10, 10, 10, 10, 10, 10, 10, 34: 10, 10, 10, 10, 69, 10, 68, 42: 64, 66, 159, 65},
		{4: 160},
		{36, 36, 36, 36, 36, 36, 36, 36, 36, 10: 36, 18: 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36},
		{95, 93, 94, 92, 5: 46, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 46, 33: 126, 41: 165},
		// 100
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 163},
		{97, 102, 103, 19: 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 100, 32: 164},
		{31, 31, 31, 31, 31, 31, 31, 31, 31, 10: 31, 18: 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31},
		{5: 128, 18: 166},
		{37, 37, 37, 37, 37, 37, 37, 37, 37, 10: 37, 18: 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37},
		// 105
		{4: 47, 128, 47, 47, 47, 31: 47},
		{97, 102, 103, 169, 19: 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 100},
		{10, 10, 10, 10, 10, 10, 70, 8: 67, 10, 10, 10, 10, 10, 10, 10, 10, 10, 34: 10, 10, 10, 10, 69, 10, 68, 42: 64, 66, 170, 65},
		{4: 171},
		{4: 50, 6: 50, 50, 50, 31: 50},
		// 110
		{10, 10, 10, 10, 10, 10, 70, 8: 67, 10, 10, 10, 10, 10, 10, 10, 10, 10, 34: 10, 10, 10, 10, 69, 10, 68, 42: 64, 66, 173, 65},
		{4: 174},
		{4: 54, 6: 54, 54, 54},
		{3: 177, 34: 176},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 180},
		// 115
		{10, 10, 10, 10, 10, 10, 70, 8: 67, 10, 10, 10, 10, 10, 10, 10, 10, 10, 34: 10, 10, 10, 10, 69, 10, 68, 42: 64, 66, 178, 65},
		{4: 179},
		{4: 48, 6: 48, 48, 48, 31: 48},
		{97, 102, 103, 181, 19: 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 100},
		{10, 10, 10, 10, 10, 10, 70, 8: 67, 10, 10, 10, 10, 10, 10, 10, 10, 10, 34: 10, 10, 10, 10, 69, 10, 68, 42: 64, 66, 182, 65},
		// 120
		{4: 183},
		{4: 49, 6: 49, 49, 49, 31: 49},
		{95, 93, 94, 92, 46, 46, 46, 46, 46, 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 126, 41: 185},
		{4: 56, 128, 56, 56, 56},
		{95, 93, 94, 92, 9: 84, 11: 88, 90, 91, 89, 85, 86, 87, 33: 187},
		// 125
		{97, 102, 103, 4: 57, 6: 57, 57, 57, 19: 106, 104, 105, 110, 109, 98, 101, 107, 111, 112, 108, 100},
		{4: 59, 6: 59, 59, 59},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 51

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yyVAL.stmts = nil
		}
	case 2:
		{
			yyVAL.stmts = yyS[yypt-1].stmts
			yylex.(*Lexer).result = yyVAL.stmts
		}
	case 3:
		{
			yyVAL.stmts = []ast.Stmt{yyS[yypt-0].stmt}
		}
	case 4:
		{
			yyVAL.stmts = append(yyS[yypt-2].stmts, yyS[yypt-0].stmt)
		}
	case 5:
		{
			yyVAL.stmt = &ast.AssStmt{Left: []ast.Expr{yyS[yypt-2].expr}, Right: []ast.Expr{yyS[yypt-0].expr}}
		}
	case 6:
		{
			yyVAL.stmt = &ast.AssStmt{Left: yyS[yypt-2].exprs, Right: yyS[yypt-0].exprs}
		}
	case 7:
		{
			yyVAL.stmt = yyS[yypt-0].stmt_if
		}
	case 8:
		{
			yyVAL.stmt = &ast.LoopStmt{Stmts: yyS[yypt-1].stmts}
		}
	case 9:
		{
			yyVAL.stmt = &ast.BreakStmt{}
		}
	case 10:
		{
			yyVAL.stmt = &ast.ContinueStmt{}
		}
	case 11:
		{
			yyVAL.stmt = &ast.ExprStmt{Expr: yyS[yypt-0].expr}
		}
	case 12:
		{
			yyVAL.stmt_if = &ast.IfStmt{If: yyS[yypt-3].expr, Then: yyS[yypt-1].stmts, Else: nil}
		}
	case 13:
		{
			yyVAL.stmt_if.(*ast.IfStmt).ElseIf = append(yyVAL.stmt_if.(*ast.IfStmt).ElseIf, &ast.IfStmt{If: yyS[yypt-3].expr, Then: yyS[yypt-1].stmts})
		}
	case 14:
		{
			if yyVAL.stmt_if.(*ast.IfStmt).Else != nil {
				yylex.Error("multiple else statement")
			} else {
				//$$.(*ast.IfStmt).Else = append($$.(*ast.IfStmt).Else, $4...)
				yyVAL.stmt_if.(*ast.IfStmt).Else = yyS[yypt-1].stmts
			}
		}
	case 15:
		{
			yyVAL.stmt_if = &ast.ReturnStmt{Exprs: yyS[yypt-0].exprs}
		}
	case 16:
		{
			yyVAL.exprs = nil
		}
	case 17:
		{
			yyVAL.exprs = []ast.Expr{yyS[yypt-0].expr}
		}
	case 18:
		{
			yyVAL.exprs = append(yyS[yypt-3].exprs, yyS[yypt-0].expr)
		}
	case 19:
		{
			yyVAL.expr = &ast.IdentExpr{Literal: yyS[yypt-0].token.Literal}
		}
	case 20:
		{
			yyVAL.expr = &ast.NumExpr{Literal: yyS[yypt-0].token.Literal}
		}
	case 21:
		{
			yyVAL.expr = &ast.StringExpr{Literal: yyS[yypt-0].token.Literal}
		}
	case 22:
		{
			yyVAL.expr = &ast.ConstExpr{Literal: yyS[yypt-0].token.Literal}
		}
	case 23:
		{
			yyVAL.expr = &ast.ConstExpr{Literal: yyS[yypt-0].token.Literal}
		}
	case 24:
		{
			yyVAL.expr = &ast.ConstExpr{Literal: yyS[yypt-0].token.Literal}
		}
	case 25:
		{
			yyVAL.expr = &ast.CallExpr{Name: yyS[yypt-3].token.Literal, SubExprs: yyS[yypt-1].exprs}
		}
	case 26:
		{
			yyVAL.expr = &ast.FuncExpr{Name: yyS[yypt-6].token.Literal, Args: yyS[yypt-4].ident_args, Stmts: yyS[yypt-1].stmts}
		}
	case 27:
		{
			yyVAL.expr = &ast.LenExpr{Expr: yyS[yypt-1].expr}
		}
	case 28:
		{
			yyVAL.expr = &ast.AnonymousCallExpr{Expr: yyS[yypt-3].expr, SubExprs: yyS[yypt-1].exprs}
		}
	case 29:
		{
			yyVAL.expr = &ast.FuncExpr{Args: yyS[yypt-4].ident_args, Stmts: yyS[yypt-1].stmts}
		}
	case 30:
		{
			yyVAL.expr = &ast.ArrayExpr{Exprs: yyS[yypt-2].exprs}
		}
	case 31:
		{
			yyVAL.expr = &ast.ItemExpr{Value: &ast.IdentExpr{Literal: yyS[yypt-3].token.Literal}, Index: yyS[yypt-1].expr}
		}
	case 32:
		{
			yyVAL.expr = &ast.ItemExpr{Value: yyS[yypt-3].expr, Index: yyS[yypt-1].exprs}
		}
	case 33:
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "+", Expr: yyS[yypt-0].expr}
		}
	case 34:
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "-", Expr: yyS[yypt-0].expr}
		}
	case 35:
		{
			yyVAL.expr = &ast.ParentExpr{SubExpr: yyS[yypt-1].expr}
		}
	case 36:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "||", Right: yyS[yypt-0].expr}
		}
	case 37:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "&&", Right: yyS[yypt-0].expr}
		}
	case 38:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "+", Right: yyS[yypt-0].expr}
		}
	case 39:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "-", Right: yyS[yypt-0].expr}
		}
	case 40:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "*", Right: yyS[yypt-0].expr}
		}
	case 41:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "/", Right: yyS[yypt-0].expr}
		}
	case 42:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "%", Right: yyS[yypt-0].expr}
		}
	case 43:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "==", Right: yyS[yypt-0].expr}
		}
	case 44:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "!=", Right: yyS[yypt-0].expr}
		}
	case 45:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: ">", Right: yyS[yypt-0].expr}
		}
	case 46:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "<", Right: yyS[yypt-0].expr}
		}
	case 47:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: ">=", Right: yyS[yypt-0].expr}
		}
	case 48:
		{
			yyVAL.expr = &ast.BinOpExpr{Left: yyS[yypt-2].expr, Operator: "<=", Right: yyS[yypt-0].expr}
		}
	case 49:
		{
			yyVAL.ident_args = []string{}
		}
	case 50:
		{
			yyVAL.ident_args = []string{yyS[yypt-0].token.Literal}
		}
	case 51:
		{
			yyVAL.ident_args = append(yyS[yypt-3].ident_args, yyS[yypt-0].token.Literal)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
